name: Build
on:
  push:
    branches:
      - develop
      - feature/IntegrationTests
  pull_request:
    branches:
        - develop
        - feature/IntegrationTests
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: sairamk-works_asn1-specification-splitter
          SONAR_ORGANIZATION: sairamk-works
